"""initial schema

Revision ID: b7145b1e85b6
Revises: 
Create Date: 2026-06-19 18:21:48.185453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7145b1e85b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('is_scrum_master', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sprints_project_id'), ['project_id'], unique=False)

    op.create_table('stakeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='stakeholder_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakeholders_status'), ['status'], unique=False)

    op.create_table('stakeholder_role_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MAIN_SPONSOR', 'VENUE_SPONSOR', 'IN_KIND_SPONSOR', 'JUDGE', 'MENTOR', 'SPEAKER', 'GUEST', name='stakeholder_role'), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stakeholder_id', 'role', name='uq_stakeholder_role')
    )
    with op.batch_alter_table('stakeholder_role_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholder_role_links_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakeholder_role_links_stakeholder_id'), ['stakeholder_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', name='task_state'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_is_blocked'), ['is_blocked'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_stakeholder_id'), ['stakeholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index(batch_op.f('ix_tasks_stakeholder_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_blocked'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))

    op.drop_table('tasks')
    with op.batch_alter_table('stakeholder_role_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholder_role_links_stakeholder_id'))
        batch_op.drop_index(batch_op.f('ix_stakeholder_role_links_role'))

    op.drop_table('stakeholder_role_links')
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholders_status'))
        batch_op.drop_index(batch_op.f('ix_stakeholders_project_id'))

    op.drop_table('stakeholders')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_project_id'))
        batch_op.drop_index(batch_op.f('ix_sprints_is_active'))

    op.drop_table('sprints')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_user_id'))

    op.drop_table('otp_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
